/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import controladores.ControlaJogos;
import entidades.Jogos;
import entidades.Jogos;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author guilherme.schorr
 */
public class TelaJogos extends javax.swing.JInternalFrame {

    ControlaJogos controlaJogos = new ControlaJogos();
    int codigo = 0;

    public TelaJogos() {
        initComponents();
        montaTabela();
    }
     private void montaTabela() {
        ArrayList<Jogos> jogos = controlaJogos.recuperarTodos();
        if (jogos == null) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar jogos");
        } else {
            tblJogos.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Quantidade";
                        case 3: 
                            return "Preço";
                        
                    }
                    return null;
                }

                @Override
                public int getColumnCount() {
                    return 4;
                }

                @Override
                public int getRowCount() {
                    return jogos.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Jogos j = jogos.get(rowIndex);

                    if (j != null) {
                        switch (columnIndex) {
                            case 0:
                                return j.getId();
                            case 1:
                                return j.getNome();
                            case 2:
                                return j.getQuantidadeEstoque();
                            case 3:
                                return j.getPreco();
                            
                        }

                    }

                    return "n/d";
                }
            });

            tblJogos.getColumnModel().getColumn(0).setMinWidth(80);
            tblJogos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblJogos.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }


    /**
     * Creates new form TelaJogos
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containertabela = new javax.swing.JTabbedPane();
        tabCadastro = new javax.swing.JPanel();
        txtNomeJogos = new javax.swing.JTextField();
        lblNomeJogos = new javax.swing.JLabel();
        lblpreco = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        lblquantidade = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        txtidjogos = new javax.swing.JTextField();
        btnsalvarjogos = new javax.swing.JButton();
        tabListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        txtNomeJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeJogosActionPerformed(evt);
            }
        });

        lblNomeJogos.setText("Nome");

        lblpreco.setText("Preço");

        lblquantidade.setText("Quantidade");

        txtquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantidadeActionPerformed(evt);
            }
        });

        txtidjogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidjogosActionPerformed(evt);
            }
        });

        btnsalvarjogos.setBackground(new java.awt.Color(255, 255, 0));
        btnsalvarjogos.setText("Salvar");
        btnsalvarjogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarjogosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastroLayout = new javax.swing.GroupLayout(tabCadastro);
        tabCadastro.setLayout(tabCadastroLayout);
        tabCadastroLayout.setHorizontalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(txtNomeJogos, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addGap(222, 222, 222))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(lblNomeJogos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpreco)
                            .addComponent(lblquantidade)
                            .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 168, Short.MAX_VALUE))))
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addComponent(txtidjogos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalvarjogos)
                .addGap(38, 38, 38))
        );
        tabCadastroLayout.setVerticalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNomeJogos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeJogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(lblquantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addComponent(lblpreco, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidjogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalvarjogos))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        containertabela.addTab("Cadastro Jogos", tabCadastro);

        tblJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJogos);

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabListagemLayout = new javax.swing.GroupLayout(tabListagem);
        tabListagem.setLayout(tabListagemLayout);
        tabListagemLayout.setHorizontalGroup(
            tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabListagemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(23, 23, 23))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        tabListagemLayout.setVerticalGroup(
            tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        containertabela.addTab("Listagem Jogos", tabListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(containertabela, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(containertabela, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeJogosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeJogosActionPerformed

    private void txtquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantidadeActionPerformed

    private void txtidjogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidjogosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidjogosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        montaTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     String idString = String.valueOf(tblJogos.getValueAt(tblJogos.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Jogos j = controlaJogos.recuperar(id);

        if (j == null) {
            JOptionPane.showMessageDialog(null, "Registro não localizado!");
        } else {

            // preenche a variavel codigo que sera usada para salvar ou editar
            codigo = j.getId();

            // mudar a aba ativa para Cadastro
            containertabela.setSelectedIndex(0);

            // coloca dados nos campos de interface
            txtNomeJogos.setText(j.getNome());
            txtquantidade.setText(String.valueOf(j.getQuantidadeEstoque()));
            txtpreco.setText(String.valueOf(j.getPreco()));
            
            txtNomeJogos.requestFocus();
        }
       
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
            String idString = String.valueOf(tblJogos.getValueAt(tblJogos.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = controlaJogos.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }
    
                                              

        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnsalvarjogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarjogosActionPerformed
        Jogos j = new Jogos();
        String nome = txtNomeJogos.getText();
        j.setNome(nome);

        String idString = txtidjogos.getText();
        int id = Integer.parseInt(idString);

        String precoString = txtpreco.getText();
        double preco = Double.parseDouble(precoString);
        j.setPreco(preco);

        String intestoque = txtquantidade.getText();
        int QuantidadeEstoque = Integer.parseInt(intestoque);
        j.setQuantidadeEstoque(QuantidadeEstoque);

        j.setId(id);

    

        if (codigo == 0) {
            boolean retorno = controlaJogos.salvar(j);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                txtNomeJogos.setText("");
                txtquantidade.setText("");
                txtpreco.setText("");

                txtNomeJogos.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        } else {
            j.setId(codigo);
            boolean retorno = controlaJogos.editar(j);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
                txtNomeJogos.setText("");
                txtquantidade.setText("");
                txtpreco.setText("");

                montaTabela();
                containertabela.setSelectedIndex(1);
                codigo = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        }
    }//GEN-LAST:event_btnsalvarjogosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnsalvarjogos;
    private javax.swing.JTabbedPane containertabela;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeJogos;
    private javax.swing.JLabel lblpreco;
    private javax.swing.JLabel lblquantidade;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JPanel tabListagem;
    private javax.swing.JTable tblJogos;
    private javax.swing.JTextField txtNomeJogos;
    private javax.swing.JTextField txtidjogos;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtquantidade;
    // End of variables declaration//GEN-END:variables
}
