/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import controladores.ControlaAvaliacoes;
import entidades.Avaliacoes;
import entidades.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author guilherme.schorr
 */
public class TelaAvaliacoes extends javax.swing.JInternalFrame {
 ControlaAvaliacoes controlaAvaliacoes = new ControlaAvaliacoes();
   int codigo = 0;
    /**
     * Creates new form TelaAvaliacoes
     */
    public TelaAvaliacoes() {
        initComponents();
    }
    private void montaTabela() {
        ArrayList<Avaliacoes> Aval = controlaAvaliacoes.recuperarTodos();
        if (Aval == null) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar jogos");
        } else {
            tblAvaliacoes.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Jogo";
                        case 3: 
                            return "Nota";
                        case 4:
                            return "Comentário";
                    }
                    return null;
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public int getRowCount() {
                    return Aval.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Avaliacoes a = Aval.get(rowIndex);

                    if (a != null) {
                        switch (columnIndex) {
                            case 0:
                                return a.getId();
                            case 1:
                                return a.getNome();
                            case 2:
                                return a.getJogo();
                            case 3:
                                return a.getNota();
                            case 4:
                                return a.getComentario();
                            
                        }

                    }

                    return "n/d";
                }
            });

            tblAvaliacoes.getColumnModel().getColumn(0).setMinWidth(80);
            tblAvaliacoes.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAvaliacoes.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containertabela = new javax.swing.JTabbedPane();
        tabAval = new javax.swing.JPanel();
        lblNomeAval = new javax.swing.JLabel();
        txtNomeAval = new javax.swing.JTextField();
        lblJogoAval = new javax.swing.JLabel();
        txtJogoAval = new javax.swing.JTextField();
        lblNotaAval = new javax.swing.JLabel();
        txtNotaAval = new javax.swing.JTextField();
        lblComentarioAval = new javax.swing.JLabel();
        txtComentarioAval = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        txtIdAval = new javax.swing.JTextField();
        tabListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvaliacoes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        lblNomeAval.setText("Nome");

        txtNomeAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAvalActionPerformed(evt);
            }
        });

        lblJogoAval.setText("Jogo");

        lblNotaAval.setText("Nota");

        lblComentarioAval.setText("Comentário");

        btnSalvar.setBackground(new java.awt.Color(255, 255, 102));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAvalLayout = new javax.swing.GroupLayout(tabAval);
        tabAval.setLayout(tabAvalLayout);
        tabAvalLayout.setHorizontalGroup(
            tabAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAvalLayout.createSequentialGroup()
                .addGroup(tabAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAvalLayout.createSequentialGroup()
                        .addComponent(txtIdAval, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addComponent(txtNotaAval)
                    .addComponent(txtComentarioAval)
                    .addGroup(tabAvalLayout.createSequentialGroup()
                        .addGroup(tabAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJogoAval, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeAval)
                            .addComponent(lblJogoAval)
                            .addComponent(lblNotaAval)
                            .addComponent(lblComentarioAval))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabAvalLayout.setVerticalGroup(
            tabAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAvalLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblNomeAval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJogoAval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJogoAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotaAval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotaAval, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentarioAval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComentarioAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tabAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAvalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAvalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIdAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        containertabela.addTab("Avaliação", tabAval);

        tblAvaliacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAvaliacoes);

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabListagemLayout = new javax.swing.GroupLayout(tabListagem);
        tabListagem.setLayout(tabListagemLayout);
        tabListagemLayout.setHorizontalGroup(
            tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabListagemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(23, 23, 23))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        tabListagemLayout.setVerticalGroup(
            tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        containertabela.addTab("Listagem de Avaliações", tabListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(containertabela, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containertabela, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAvalActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Avaliacoes Aval = new Avaliacoes();
        String nome = txtNomeAval.getText();
        Aval.setNome(nome);
        Aval.setJogo(txtJogoAval.getText());
      
        String intnota = txtNotaAval.getText();
        int NotaAval = Integer.parseInt(intnota);
        Aval.setNota(NotaAval);
        
        Aval.setComentario(txtComentarioAval.getText());
        String idString = txtIdAval.getText();
        int id = Integer.parseInt(idString);
        Aval.setId(id);

        System.out.println(Aval);

         if (codigo == 0) {
            boolean retorno = controlaAvaliacoes.salvar(Aval);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                txtNomeAval.setText("");
                txtJogoAval.setText("");
                txtNotaAval.setText("");
                txtComentarioAval.setText("");

                txtNomeAval.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        } else {
            Aval.setId(codigo);
            boolean retorno = controlaAvaliacoes.editar(Aval);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
                txtNomeAval.setText("");
                txtJogoAval.setText("");
                txtNotaAval.setText("");
                txtComentarioAval.setText("");

                montaTabela();
                containertabela.setSelectedIndex(1);
                codigo = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        montaTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        String idString = String.valueOf(tblAvaliacoes.getValueAt(tblAvaliacoes.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = controlaAvaliacoes.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
  String idString = String.valueOf(tblAvaliacoes.getValueAt(tblAvaliacoes.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Avaliacoes Aval = controlaAvaliacoes.recuperar(id);

        if (Aval == null) {
            JOptionPane.showMessageDialog(null, "Registro não localizado!");
        } else {

            // preenche a variavel codigo que sera usada para salvar ou editar
            codigo = Aval.getId();

            // mudar a aba ativa para Cadastro
            containertabela.setSelectedIndex(0);

            // coloca dados nos campos de interface
            txtNomeAval.setText(Aval.getNome());
            txtJogoAval.setText(Aval.getJogo());
           txtNotaAval.setText(String.valueOf(Aval.getNota()));
            txtComentarioAval.setText(Aval.getComentario());

            txtNomeAval.requestFocus();
        }

    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTabbedPane containertabela;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComentarioAval;
    private javax.swing.JLabel lblJogoAval;
    private javax.swing.JLabel lblNomeAval;
    private javax.swing.JLabel lblNotaAval;
    private javax.swing.JPanel tabAval;
    private javax.swing.JPanel tabListagem;
    private javax.swing.JTable tblAvaliacoes;
    private javax.swing.JTextField txtComentarioAval;
    private javax.swing.JTextField txtIdAval;
    private javax.swing.JTextField txtJogoAval;
    private javax.swing.JTextField txtNomeAval;
    private javax.swing.JTextField txtNotaAval;
    // End of variables declaration//GEN-END:variables
}
